== Familiar and Unfamiliar Quotations

== About http://norvig.com/quotations.html#life[Life], http://norvig.com/quotations.html#universe[The Universe], http://norvig.com/quotations.html#computers[Computers,] and http://norvig.com/quotations.html#everything[Everything]

'''''

[#life]##

[cols="",]
|===
|*Life*
|===

Always do right. This will gratify some people and astonish the rest. +
_    - http://en.wikipedia.org/wiki/Mark_twain[Mark Twain]_

A man is a success if he gets up in the morning and gets to bed at
night, and in between he does what he wants to do. +
_    - http://en.wikipedia.org/wiki/Bob_Dylan[Bob Dylan]_

Don't wait for the Last Judgement. It takes place every day. +
_    - http://en.wikipedia.org/wiki/Albert_Camus[Albert Camus]_

Brick walls are there for a reason. They're not there to keep us out.
The brick walls are there to give us a chance to show how badly we want
something. +
_    - http://randypausch.com/[Randy Pausch]_

Far and away the best prize life has to offer is the chance to work hard
at work worth doing. +
_    - http://en.wikipedia.org/wiki/Theodore_Roosevelt[Theodore
Roosevelt]_

I cannot afford to waste my time making money. +
_    - http://en.wikipedia.org/wiki/Louis_Agassiz[Louis Agassiz]_

All you have to decide is what you're going to do with the time you are
given. +
_    - http://en.wikipedia.org/wiki/Gandalf[Gandalf]_

The quality of a person's life is in direct proportion to their
commitment to excellence, regardless of their field of endeavor. +
_    - http://www.vincelombardi.com/[Vince Lombardi]_

No art, however minor, demands less than total dedication if you want to
excel in it. +
_    - http://en.wikipedia.org/wiki/Leone_Battista_Alberti[Leon Battista
Alberti], (architect, painter and mathematician)_

My crystal ball is fuzzy +
_    -
http://www.cs.berkeley.edu/People/Faculty/Homepages/zadeh.html[Lotfi
Zadeh] (inventor of Fuzzy Logic, when asked to predict the future)_

If I had a dollar for every million-dollar idea I've had, I'd be rich. +
_    - http://www.compliancemedia.com/Principals.html[Greg Meyer]_

There's nothing that will change someone's moral outlook quicker than
cash in large sums. +
_    - http://en.wikipedia.org/wiki/Larry_Flynt[Larry Flynt]_

The perfect is the enemy of the good. +
_    - http://en.wikipedia.org/wiki/Voltaire[Voltaire]_

I have great faith in fools. Self-confidence, my friends call it. +
_    - http://en.wikipedia.org/wiki/Edgar_Allan_Poe[Edgar Allen Poe]_

The point of all this is to be able to spend more time at the beach! +
_    - http://robotics.stanford.edu/users/nilsson/bio.html[Nils
Nilsson]_

Being famous has its benefits, but fame isn't one of them. +
_    - http://www.wall.org/~larry/[Larry Wall]_

Personally, I liked the university. They gave us money and facilities,
we didn't have to produce anything! You've never been out of college!
You don't know what it's like out there! I've _worked_ in the private
sector. They expect _results_. +
_    - http://www.imdb.com/name/nm0000101/[Dr Ray Stanz (Dan Aykroyd)],
Ghostbusters_

A great many people think they are thinking when they are merely
rearranging their prejudices. +
_    - http://en.wikipedia.org/wiki/William_James[William James]_

It is the mark of an educated mind to be able to entertain a thought
without accepting it. +
_    - http://en.wikipedia.org/wiki/Aristotle[Aristotle]_

I try to leave out the parts that people skip. +
_    - http://en.wikipedia.org/Elmore_Leonard[Elmore Leonard] (on his
secret to writing)_

Either write something worth reading or do something worth writing. +
_    - http://en.wikipedia.org/wiki/Benjamin_Franklin[Benjamin
Franklin]_

Believe, if thou wilt, that mountains change their place, but believe
not that man changes his nature. +
_    - http://en.wikipedia.org/wiki/Mohammed[Mohammed]_

[#universe]##

[cols="",]
|===
|*The Universe*
|===

In the beginning, the Universe was created. This has made a lot of
people very angry and been widely regarded as a bad move. +
_    - http://www.douglasadams.com/[Douglas Adams]_

Space isn't remote at all. It's only an hour's drive away if your car
could go straight upwards. +
_    - http://en.wikipedia.org/wiki/Fred_Hoyle[Fred Hoyle]_

Man is the best computer we can put aboard a spacecraft... and the only
one that can be mass produced with unskilled labor. +
_    -
http://liftoff.msfc.nasa.gov/academy/history/vonBraun/vonBraun.html[Wernher
von Braun]_

We can lick gravity, but sometimes the paperwork is overwhelming. +
_    -
http://liftoff.msfc.nasa.gov/academy/history/vonBraun/vonBraun.html[Wernher
von Braun]_

I don't see any god up here. +
_    - http://en.wikipedia.org/wiki/Gagarin[Yuri Gagarin] (in orbit,
1961)_

Only two things are infinite, the universe and human stupidity, and I'm
not sure about the former. +
_    - http://en.wikipedia.org/wiki/Einstein[Albert Einstein]_

There are 10^11^ stars in the galaxy. That used to be a _huge_ number.
But it's only a hundred billion. It's less than the national deficit! We
used to call them astronomical numbers. Now we should call them
economical numbers. +
_    - http://www.feynmanonline.com/[Richard Feynman]_

For all our conceits about being the center of the universe, we live in
a routine planet of a humdrum star stuck away in an obscure corner ...
on an unexceptional galaxy which is one of about 100 billion galaxies.
... That is the fundamental fact of the universe we inhabit, and it is
very good for us to understand that. +
_    - http://en.wikipedia.org/wiki/Carl_Sagan[Carl Sagan]_

Far out in the uncharted backwaters of the unfashionable end of the
Western Spiral arm of the Galaxy lies a small unregarded yellow sun.
Orbiting this at a distance of roughly ninety-eight million miles is an
utterly insignificant little blue-green planet whose ape-descended life
forms are so amazingly primitive that they still think digital watches
are a pretty neat idea. +
_    - http://www.douglasadams.com/[Douglas Adams]_

[#computers]##

[cols="",]
|===
|*Computers*
|===

Some software is actually pretty good, by any standard. Think of the
Mars Rovers, Google, and the Human Genome Project. Now, that's quality
software! +
_    - http://parasol.tamu.edu/people/bs/[Bjarne Stroustrup], (when
asked by http://www.technologyreview.com/Infotech/17987/?a=f[Technology
Review] "Why is software so bad?". I'm proud to have worked on two of
those three projects.)_

The world has arrived at an age of cheap complex devices of great
reliability; and something is bound to come of it. +
_    - http://en.wikipedia.org/wiki/Vannevar_Bush[Vannevar Bush] (1945)_

Power corrupts, and obsolete power corrupts obsoletely. +
_    - http://en.wikipedia.org/wiki/Ted_Nelson[Ted Nelson], on the
Microsoft DOS operating system_

Computers make it easier to do a lot of things, but most of the things
they make it easier to do don't need to be done +
_    - http://en.wikipedia.org/wiki/Andy_Rooney[Andy Rooney]_

As soon as we started programming, we found out to our surprise that it
wasn't as easy to get programs right as we had thought. Debugging had to
be discovered. I can remember the exact instant when I realized that a
large part of my life from then on was going to be spent in finding
mistakes in my own programs. +
_    - http://en.wikipedia.org/wiki/Maurice_Wilkes[Maurice Wilkes]_

Only wimps use tape backup: _real_ men just upload their important stuff
on ftp, and let the rest of the world mirror it. +
_    - http://en.wikipedia.org/wiki/Linus_Torvalds[Linus Torvalds]_

C++ is history repeated as tragedy. Java is history repeated as farce. +
_    - mailto:swm@mediaone.net[Scott McKay]_

Nothing is destroyed until it is replaced. +
_    - http://en.wikipedia.org/wiki/Auguste_Comte[Auguste Comte
(1798-1857)] (on the need for revolutionary new theories (or on the need
to do `x.f = null` in garbage-collected languages with destructors))_

In general, they do what you want, unless you want consistency. +
_    - http://www.wall.org/~larry/[Larry Wall] (on Perl functions)_

Computer language design is just like a stroll in the park. Jurassic
Park, that is. +
_    - http://www.wall.org/~larry/[Larry Wall]_

If you give someone Fortran, he has Fortran. If you give someone Lisp,
he has any language he pleases. +
_    - http://en.wikipedia.org/wiki/Guy_Steele[Guy L. Steele]_

[Lisp] is the only computer language that is beautiful. +
_    - http://en.wikipedia.org/wiki/Neal_Stephenson[Neal Stephenson]_

If you can't hear me, it's because I'm in parentheses. +
_    - http://en.wikipedia.org/wiki/Steven_Wright[Steven Wright]_

He who refuses to do arithmetic is doomed to talk nonsense. +
_    - http://www-formal.stanford.edu/jmc/[John McCarthy]_

Belief is no substitute for arithmetic. +
_    - http://www.lysator.liu.se/c/henry/[Henry Spencer]_

Object-oriented programming is an exceptionally bad idea which could
only have originated in California. +
_    -
http://www.cs.utexas.edu/users/UTCS/report/1994/profiles/dijkstra.html[Edsger
Dijkstra] (attributed)_

We read Knuth so you don't have to. +
_    -http://c2.com/cgi/wiki?TimPeters[Tim Peters] (explaining what the
Python developers do in their spare time)_

Computers are useless. They can only give you answers. +
_    - http://en.wikipedia.org/wiki/Picasso[Pablo Picasso]_

I do not believe in objects. I believe only in their relationships. +
_    - http://en.wikipedia.org/wiki/Braque[George Braque]_

I don't paint things. I only paint the difference between things. +
_    - http://en.wikipedia.org/wiki/Matisse[Henri Matisse]_

Mathematicians do not study objects, but relations among objects; they
are indifferent to the replacement of objects by others as long the
relations don't change. Matter is not important, only form interests
them. +
_    - http://en.wikipedia.org/wiki/Henri_Poincar%C3%A9[Henri Poincare]_

Have nothing in your houses that you do not know to be useful, or
believe to be beautiful. +
_    - http://www.morrissociety.org/[William Morris]_

All models are wrong. Some models are useful. +
_    - http://www.engr.wisc.edu/ie/faculty/box_george.html[George Box]_

When cryptography is outlawed, bayl bhgynjf jvyy unir cevinpl! +
_    - http://en.wikipedia.org/wiki/Brad_Templeton[Brad Templeton]_

Errors using inadequate data are much less than those using no data at
all. +
_    - http://en.wikipedia.org/wiki/Babbage[Charles Babbage]_

In the future, search engines should be as useful as HAL in the movie
_2001: A Space Odyssey_--but hopefully they won't kill people. +
_    - http://en.wikipedia.org/wiki/Sergey_Brin[Sergey Brin]_

[#everything]##

[cols="",]
|===
|*Everything*
|===

Doubt is not a pleasant condition, but certainty is an absurd one. +
_    - http://en.wikipedia.org/wiki/Voltaire[Voltaire]_

There are three principal ways to lose money: wine, women, and
engineers. While the first two are more pleasant, the third is by far
the more certain. +
_    - http://www.jewishpeople.net/barrot.html[Baron Rothschild]_

God is a hacker, not an engineer. +
_    - http://en.wikipedia.org/wiki/Francis_Crick[Francis Crick]_

You can do reverse engineering, but you can't do reverse hacking. +
_    - http://en.wikipedia.org/wiki/Vilayanur_S._Ramachandran[V. S.
Ramachandran]_

I have often thought that if there had been a good rap group in those
days, I might have chosen a career in music instead of politics. +
_    - http://en.wikipedia.org/wiki/Nixon[Richard Nixon]_

If I have made myself clear, you must have misunderstood me. +
_    - http://en.wikipedia.org/wiki/Greenspan[Alan Greenspan]_

Science is like sex: sometimes something useful comes out, but that is
not the reason we are doing it +
_    - http://www.feynmanonline.com/[Richard Feynman]_

Literature is mostly about having sex, and not much about having babies;
life is the other way round. +
_    - http://en.wikipedia.org/wiki/David_Lodge_%28author%29[David
Lodge]_

More than any other time in history mankind faces a crossroads. One path
leads to despair and utter hopelessness, the other to total extinction.
Let us pray we have the wisdom to choose correctly. +
_    -http://en.wikipedia.org/wiki/Woody_Allen[Woody Allen]_

When you have eliminated the impossible, whatever remains, however
improbable, must be the truth. +
_    - http://en.wikipedia.org/wiki/Arthur_Conan_Doyle[Sir Arthur Conan
Doyle]_

Chance favors only the prepared mind. +
_    - http://en.wikipedia.org/wiki/Pasteur[Louis Pasteur]_

Lord, give us the wisdom to utter words that are gentle and tender, for
tomorrow we may have to eat them. +
_    -http://www.udall.gov/mku.htm[Sen. Morris Udall]_

It does not require a majority to prevail, but rather an irate, tireless
minority keen to set brush fires in people's minds. +
_    - http://www.samadams.com/[Samuel Adams]_

I don't want to achieve immortality through my work ... I want to
achieve it through not dying. +
_    - http://en.wikipedia.org/wiki/Woody_allen[Woody Allen]_

I am a man of fixed and unbending principles, the first of which is to
be flexible at all times. +
_    - http://en.wikipedia.org/wiki/Dirksen[Sen. Everett Dirksen]_

When I face an issue of great import that cleaves both constituents and
colleagues, I always take the same approach. I engage in deep
deliberation and quiet contemplation. I wait to the last available
minute and then I always vote with the losers. Because, my friend, the
winners never remember and the losers never forget. +
_    - http://en.wikipedia.org/wiki/Dirksen[Sen. Everett Dirksen]_

Wise men make proverbs, but fools repeat them. +
_    - http://en.wikipedia.org/wiki/Samuel_Palmer[Samuel Palmer]_

In the End, we will remember not the words of our enemies, but the
silence of our friends. +
_    - http://en.wikipedia.org/wiki/Luther_King[Martin Luther King Jr.]_

In the end, everything is a gag. +
_    -
http://en.wikipedia.org/wiki/Charles_Chaplin_%28disambiguation%29[Charlie
Chaplin]_

'''''

_http://norvig.com/index.html[Peter Norvig]_
