.SH 1
Familiar and Unfamiliar Quotations
.pdfhref O 1 "Familiar and Unfamiliar Quotations"
.pdfhref M "familiar-and-unfamiliar-quotations"
.SH 1
About \c
.pdfhref W -D "http://norvig.com/quotations.html#life" -A "\c" \
 -- "Life"
\&, \c
.pdfhref W -D "http://norvig.com/quotations.html#universe" -A "\c" \
 -- "The Universe"
\&, \c
.pdfhref W -D "http://norvig.com/quotations.html#computers" -A "\c" \
 -- "Computers,"
\& and \c
.pdfhref W -D "http://norvig.com/quotations.html#everything" -A "\c" \
 -- "Everything"
\&
.pdfhref O 1 "About Life, The Universe, Computers, and Everything"
.pdfhref M "about-life-the-universe-computers-and-everything"
.HLINE
.PP
.PP
.TS
delim(@@) tab(	);
l.
T{
\f[B]Life\f[R]
T}
.TE
.LP
Always do right.
This will gratify some people and astonish the rest.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Mark_twain" -A "\c" \
 -- "Mark Twain"
\&\f[R]
.PP
A man is a success if he gets up in the morning and gets to bed at
night, and in between he does what he wants to do.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Bob_Dylan" -A "\c" \
 -- "Bob Dylan"
\&\f[R]
.PP
Don\[aq]t wait for the Last Judgement.
It takes place every day.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Albert_Camus" -A "\c" \
 -- "Albert Camus"
\&\f[R]
.PP
Brick walls are there for a reason.
They\[aq]re not there to keep us out.
The brick walls are there to give us a chance to show how badly we want
something.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://randypausch.com/" -A "\c" \
 -- "Randy Pausch"
\&\f[R]
.PP
Far and away the best prize life has to offer is the chance to work hard
at work worth doing.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Theodore_Roosevelt" -A "\c" \
 -- "Theodore Roosevelt"
\&\f[R]
.PP
I cannot afford to waste my time making money.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Louis_Agassiz" -A "\c" \
 -- "Louis Agassiz"
\&\f[R]
.PP
All you have to decide is what you\[aq]re going to do with the time you
are given.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Gandalf" -A "\c" \
 -- "Gandalf"
\&\f[R]
.PP
The quality of a person\[aq]s life is in direct proportion to their
commitment to excellence, regardless of their field of endeavor.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.vincelombardi.com/" -A "\c" \
 -- "Vince Lombardi"
\&\f[R]
.PP
No art, however minor, demands less than total dedication if you want to
excel in it.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Leone_Battista_Alberti" -A "\c" \
 -- "Leon Battista Alberti"
\&, (architect, painter and mathematician)\f[R]
.PP
My crystal ball is fuzzy
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.cs.berkeley.edu/People/Faculty/Homepages/zadeh.html" -A "\c" \
 -- "Lotfi Zadeh"
\& (inventor of Fuzzy Logic, when asked to predict the future)\f[R]
.PP
If I had a dollar for every million-dollar idea I\[aq]ve had, I\[aq]d be
rich.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.compliancemedia.com/Principals.html" -A "\c" \
 -- "Greg Meyer"
\&\f[R]
.PP
There\[aq]s nothing that will change someone\[aq]s moral outlook quicker
than cash in large sums.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Larry_Flynt" -A "\c" \
 -- "Larry Flynt"
\&\f[R]
.PP
The perfect is the enemy of the good.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Voltaire" -A "\c" \
 -- "Voltaire"
\&\f[R]
.PP
I have great faith in fools.
Self-confidence, my friends call it.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Edgar_Allan_Poe" -A "\c" \
 -- "Edgar Allen Poe"
\&\f[R]
.PP
The point of all this is to be able to spend more time at the beach!
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://robotics.stanford.edu/users/nilsson/bio.html" -A "\c" \
 -- "Nils Nilsson"
\&\f[R]
.PP
Being famous has its benefits, but fame isn\[aq]t one of them.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.wall.org/~larry/" -A "\c" \
 -- "Larry Wall"
\&\f[R]
.PP
Personally, I liked the university.
They gave us money and facilities, we didn\[aq]t have to produce
anything! You\[aq]ve never been out of college! You don\[aq]t know what
it\[aq]s like out there! I\[aq]ve \f[I]worked\f[R] in the private
sector.
They expect \f[I]results\f[R].
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.imdb.com/name/nm0000101/" -A "\c" \
 -- "Dr Ray Stanz (Dan Aykroyd)"
\&, Ghostbusters\f[R]
.PP
A great many people think they are thinking when they are merely
rearranging their prejudices.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/William_James" -A "\c" \
 -- "William James"
\&\f[R]
.PP
It is the mark of an educated mind to be able to entertain a thought
without accepting it.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Aristotle" -A "\c" \
 -- "Aristotle"
\&\f[R]
.PP
I try to leave out the parts that people skip.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/Elmore_Leonard" -A "\c" \
 -- "Elmore Leonard"
\& (on his secret to writing)\f[R]
.PP
Either write something worth reading or do something worth writing.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Benjamin_Franklin" -A "\c" \
 -- "Benjamin Franklin"
\&\f[R]
.PP
Believe, if thou wilt, that mountains change their place, but believe
not that man changes his nature.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Mohammed" -A "\c" \
 -- "Mohammed"
\&\f[R]
.PP
.PP
.TS
delim(@@) tab(	);
l.
T{
\f[B]The Universe\f[R]
T}
.TE
.LP
In the beginning, the Universe was created.
This has made a lot of people very angry and been widely regarded as a
bad move.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.douglasadams.com/" -A "\c" \
 -- "Douglas Adams"
\&\f[R]
.PP
Space isn\[aq]t remote at all.
It\[aq]s only an hour\[aq]s drive away if your car could go straight
upwards.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Fred_Hoyle" -A "\c" \
 -- "Fred Hoyle"
\&\f[R]
.PP
Man is the best computer we can put aboard a spacecraft...
and the only one that can be mass produced with unskilled labor.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://liftoff.msfc.nasa.gov/academy/history/vonBraun/vonBraun.html" -A "\c" \
 -- "Wernher von Braun"
\&\f[R]
.PP
We can lick gravity, but sometimes the paperwork is overwhelming.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://liftoff.msfc.nasa.gov/academy/history/vonBraun/vonBraun.html" -A "\c" \
 -- "Wernher von Braun"
\&\f[R]
.PP
I don\[aq]t see any god up here.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Gagarin" -A "\c" \
 -- "Yuri Gagarin"
\& (in orbit, 1961)\f[R]
.PP
Only two things are infinite, the universe and human stupidity, and
I\[aq]m not sure about the former.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Einstein" -A "\c" \
 -- "Albert Einstein"
\&\f[R]
.PP
There are 10\*{11\*} stars in the galaxy.
That used to be a \f[I]huge\f[R] number.
But it\[aq]s only a hundred billion.
It\[aq]s less than the national deficit! We used to call them
astronomical numbers.
Now we should call them economical numbers.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.feynmanonline.com/" -A "\c" \
 -- "Richard Feynman"
\&\f[R]
.PP
For all our conceits about being the center of the universe, we live in
a routine planet of a humdrum star stuck away in an obscure corner ...
on an unexceptional galaxy which is one of about 100 billion galaxies.
\&...
That is the fundamental fact of the universe we inhabit, and it is very
good for us to understand that.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Carl_Sagan" -A "\c" \
 -- "Carl Sagan"
\&\f[R]
.PP
Far out in the uncharted backwaters of the unfashionable end of the
Western Spiral arm of the Galaxy lies a small unregarded yellow sun.
Orbiting this at a distance of roughly ninety-eight million miles is an
utterly insignificant little blue-green planet whose ape-descended life
forms are so amazingly primitive that they still think digital watches
are a pretty neat idea.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.douglasadams.com/" -A "\c" \
 -- "Douglas Adams"
\&\f[R]
.PP
.PP
.TS
delim(@@) tab(	);
l.
T{
\f[B]Computers\f[R]
T}
.TE
.LP
Some software is actually pretty good, by any standard.
Think of the Mars Rovers, Google, and the Human Genome Project.
Now, that\[aq]s quality software!
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://parasol.tamu.edu/people/bs/" -A "\c" \
 -- "Bjarne Stroustrup"
\&, (when asked by \c
.pdfhref W -D "http://www.technologyreview.com/Infotech/17987/?a=f" -A "\c" \
 -- "Technology Review"
\& \[dq]Why is software so bad?\[dq]. I\[aq]m proud to have worked on
two of those three projects.)\f[R]
.PP
The world has arrived at an age of cheap complex devices of great
reliability; and something is bound to come of it.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Vannevar_Bush" -A "\c" \
 -- "Vannevar Bush"
\& (1945)\f[R]
.PP
Power corrupts, and obsolete power corrupts obsoletely.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Ted_Nelson" -A "\c" \
 -- "Ted Nelson"
\&, on the Microsoft DOS operating system\f[R]
.PP
Computers make it easier to do a lot of things, but most of the things
they make it easier to do don\[aq]t need to be done
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Andy_Rooney" -A "\c" \
 -- "Andy Rooney"
\&\f[R]
.PP
As soon as we started programming, we found out to our surprise that it
wasn\[aq]t as easy to get programs right as we had thought.
Debugging had to be discovered.
I can remember the exact instant when I realized that a large part of my
life from then on was going to be spent in finding mistakes in my own
programs.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Maurice_Wilkes" -A "\c" \
 -- "Maurice Wilkes"
\&\f[R]
.PP
Only wimps use tape backup: \f[I]real\f[R] men just upload their
important stuff on ftp, and let the rest of the world mirror it.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Linus_Torvalds" -A "\c" \
 -- "Linus Torvalds"
\&\f[R]
.PP
C++ is history repeated as tragedy.
Java is history repeated as farce.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "mailto:swm%40mediaone.net" -A "\c" \
 -- "Scott McKay"
\&\f[R]
.PP
Nothing is destroyed until it is replaced.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Auguste_Comte" -A "\c" \
 -- "Auguste Comte (1798-1857)"
\& (on the need for revolutionary new theories (or on the need to do
\f[CI]x.f = null\f[I] in garbage-collected languages with
destructors))\f[R]
.PP
In general, they do what you want, unless you want consistency.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.wall.org/~larry/" -A "\c" \
 -- "Larry Wall"
\& (on Perl functions)\f[R]
.PP
Computer language design is just like a stroll in the park.
Jurassic Park, that is.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.wall.org/~larry/" -A "\c" \
 -- "Larry Wall"
\&\f[R]
.PP
If you give someone Fortran, he has Fortran.
If you give someone Lisp, he has any language he pleases.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Guy_Steele" -A "\c" \
 -- "Guy L. Steele"
\&\f[R]
.PP
[Lisp] is the only computer language that is beautiful.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Neal_Stephenson" -A "\c" \
 -- "Neal Stephenson"
\&\f[R]
.PP
If you can\[aq]t hear me, it\[aq]s because I\[aq]m in parentheses.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Steven_Wright" -A "\c" \
 -- "Steven Wright"
\&\f[R]
.PP
He who refuses to do arithmetic is doomed to talk nonsense.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www-formal.stanford.edu/jmc/" -A "\c" \
 -- "John McCarthy"
\&\f[R]
.PP
Belief is no substitute for arithmetic.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.lysator.liu.se/c/henry/" -A "\c" \
 -- "Henry Spencer"
\&\f[R]
.PP
Object-oriented programming is an exceptionally bad idea which could
only have originated in California.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.cs.utexas.edu/users/UTCS/report/1994/profiles/dijkstra.html" -A "\c" \
 -- "Edsger Dijkstra"
\& (attributed)\f[R]
.PP
We read Knuth so you don\[aq]t have to.
.br
\f[I]\ \ \ \ -\c
.pdfhref W -D "http://c2.com/cgi/wiki?TimPeters" -A "\c" \
 -- "Tim Peters"
\& (explaining what the Python developers do in their spare time)\f[R]
.PP
Computers are useless.
They can only give you answers.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Picasso" -A "\c" \
 -- "Pablo Picasso"
\&\f[R]
.PP
I do not believe in objects.
I believe only in their relationships.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Braque" -A "\c" \
 -- "George Braque"
\&\f[R]
.PP
I don\[aq]t paint things.
I only paint the difference between things.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Matisse" -A "\c" \
 -- "Henri Matisse"
\&\f[R]
.PP
Mathematicians do not study objects, but relations among objects; they
are indifferent to the replacement of objects by others as long the
relations don\[aq]t change.
Matter is not important, only form interests them.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Henri_Poincar%C3%A9" -A "\c" \
 -- "Henri Poincare"
\&\f[R]
.PP
Have nothing in your houses that you do not know to be useful, or
believe to be beautiful.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.morrissociety.org/" -A "\c" \
 -- "William Morris"
\&\f[R]
.PP
All models are wrong.
Some models are useful.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.engr.wisc.edu/ie/faculty/box_george.html" -A "\c" \
 -- "George Box"
\&\f[R]
.PP
When cryptography is outlawed, bayl bhgynjf jvyy unir cevinpl!
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Brad_Templeton" -A "\c" \
 -- "Brad Templeton"
\&\f[R]
.PP
Errors using inadequate data are much less than those using no data at
all.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Babbage" -A "\c" \
 -- "Charles Babbage"
\&\f[R]
.PP
In the future, search engines should be as useful as HAL in the movie
\f[I]2001: A Space Odyssey\f[R]--but hopefully they won\[aq]t kill
people.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Sergey_Brin" -A "\c" \
 -- "Sergey Brin"
\&\f[R]
.PP
.PP
.TS
delim(@@) tab(	);
l.
T{
\f[B]Everything\f[R]
T}
.TE
.LP
Doubt is not a pleasant condition, but certainty is an absurd one.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Voltaire" -A "\c" \
 -- "Voltaire"
\&\f[R]
.PP
There are three principal ways to lose money: wine, women, and
engineers.
While the first two are more pleasant, the third is by far the more
certain.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.jewishpeople.net/barrot.html" -A "\c" \
 -- "Baron Rothschild"
\&\f[R]
.PP
God is a hacker, not an engineer.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Francis_Crick" -A "\c" \
 -- "Francis Crick"
\&\f[R]
.PP
You can do reverse engineering, but you can\[aq]t do reverse hacking.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Vilayanur_S._Ramachandran" -A "\c" \
 -- "V. S. Ramachandran"
\&\f[R]
.PP
I have often thought that if there had been a good rap group in those
days, I might have chosen a career in music instead of politics.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Nixon" -A "\c" \
 -- "Richard Nixon"
\&\f[R]
.PP
If I have made myself clear, you must have misunderstood me.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Greenspan" -A "\c" \
 -- "Alan Greenspan"
\&\f[R]
.PP
Science is like sex: sometimes something useful comes out, but that is
not the reason we are doing it
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.feynmanonline.com/" -A "\c" \
 -- "Richard Feynman"
\&\f[R]
.PP
Literature is mostly about having sex, and not much about having babies;
life is the other way round.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/David_Lodge_%28author%29" -A "\c" \
 -- "David Lodge"
\&\f[R]
.PP
More than any other time in history mankind faces a crossroads.
One path leads to despair and utter hopelessness, the other to total
extinction.
Let us pray we have the wisdom to choose correctly.
.br
\f[I]\ \ \ \ -\c
.pdfhref W -D "http://en.wikipedia.org/wiki/Woody_Allen" -A "\c" \
 -- "Woody Allen"
\&\f[R]
.PP
When you have eliminated the impossible, whatever remains, however
improbable, must be the truth.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Arthur_Conan_Doyle" -A "\c" \
 -- "Sir Arthur Conan Doyle"
\&\f[R]
.PP
Chance favors only the prepared mind.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Pasteur" -A "\c" \
 -- "Louis Pasteur"
\&\f[R]
.PP
Lord, give us the wisdom to utter words that are gentle and tender, for
tomorrow we may have to eat them.
.br
\f[I]\ \ \ \ -\c
.pdfhref W -D "http://www.udall.gov/mku.htm" -A "\c" \
 -- "Sen. Morris Udall"
\&\f[R]
.PP
It does not require a majority to prevail, but rather an irate, tireless
minority keen to set brush fires in people\[aq]s minds.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://www.samadams.com/" -A "\c" \
 -- "Samuel Adams"
\&\f[R]
.PP
I don\[aq]t want to achieve immortality through my work ...
I want to achieve it through not dying.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Woody_allen" -A "\c" \
 -- "Woody Allen"
\&\f[R]
.PP
I am a man of fixed and unbending principles, the first of which is to
be flexible at all times.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Dirksen" -A "\c" \
 -- "Sen. Everett Dirksen"
\&\f[R]
.PP
When I face an issue of great import that cleaves both constituents and
colleagues, I always take the same approach.
I engage in deep deliberation and quiet contemplation.
I wait to the last available minute and then I always vote with the
losers.
Because, my friend, the winners never remember and the losers never
forget.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Dirksen" -A "\c" \
 -- "Sen. Everett Dirksen"
\&\f[R]
.PP
Wise men make proverbs, but fools repeat them.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Samuel_Palmer" -A "\c" \
 -- "Samuel Palmer"
\&\f[R]
.PP
In the End, we will remember not the words of our enemies, but the
silence of our friends.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Luther_King" -A "\c" \
 -- "Martin Luther King Jr."
\&\f[R]
.PP
In the end, everything is a gag.
.br
\f[I]\ \ \ \ - \c
.pdfhref W -D "http://en.wikipedia.org/wiki/Charles_Chaplin_%28disambiguation%29" -A "\c" \
 -- "Charlie Chaplin"
\&\f[R]
.HLINE
.PP
\f[I]\c
.pdfhref W -D "http://norvig.com/index.html" -A "\c" \
 -- "Peter Norvig"
\&\f[R]
